### ISSUE TITLE
Todo list early 2019

### ISSUE THREAD

**Issue by Juliacare** [pinano-discord/Pinano-Discord-Bot#11]
# High priority

- [x] Moderation tool, flag messages for review depending on words used

# Features

- [ ] Turn Leaderboard commands into the graphical cards, similar to p!stats
- [ ] Achievements
- [x] Automatic VC creation and deletion depending on activity
- [ ] Sheet music search function
- [ ] Translate sheet music search function to JS 
- [x] Moderation tool, flag messages for review depending on words used
- [x] Macros  ( #10 ) @Juliacare 
~~- [ ] Assign active pracker to people who are on the leaderboard at the end of the week~~ we're not doing this anymore

# Enhancements

- [ ] Change text on level cards from p!stats to use impact and #ff9600
- [x] Rewrite the bot to make it more readable and to remove errors  ( #8 ) @pianiststickman @sit 
- [x] Make p!stats usable on other people
- [x] Use role name instead of ID for the 40 hour pracker and active pracker role assigner

# Bug fixes

- [x] #9 @pianiststickman 

# Other

- [x] Move the bot into a organization repository instead of a personal repository @ubermadness

**Comment by pianiststickman** [comment]
Gonna open individual items.
